main: main.cpp
	g++ -std=c++17 -O2 main.cpp -o main.exe
run: main.exe
	./main.exe -type=All
runA: main.exe
	./main.exe -type=Dirichlet
runB: main.exe
	./main.exe -type=Neumann
runC: main.exe
	./main.exe -type=Mixed
runD: main.exe
	./main.exe -type=Dirichlet_Special
runE: main.exe
	./main.exe -type=Mixed_Special